name: Hello Actions
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # schedule:
  #   - cron: '0 12 * * 1' # Every Monday at 12:00 PM UTC
  workflow_dispatch:
jobs:
  hello-actions-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

  good-bye-job:
    runs-on: ubuntu-latest
    steps:
      - name: Say Goodbye
        run: echo "Goodbye from GitHub Actions! Have a great day!"
        
