name: Hello Actions
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 12 * * 1' # Every Monday at 12:00 PM UTC
  workflow_dispatch:
jobs:
  hello-actions-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Event name: ${{ github.event_name }}"
          echo "Actor: ${{ github.actor }}"
          echo "Workflow run ID: ${{ github.run_id }}"
        with:
          fetch-depth: 1

  good-bye-job:
    runs-on: ubuntu-latest
    steps:
      - name: Say Goodbye
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Event name: ${{ github.event_name }}"
          echo "Actor: ${{ github.actor }}"
          echo "Workflow run ID: ${{ github.run_id }}"
