name: Hello Actions
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 12 * * *' # Runs daily at noon UTC
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  hello-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Greet the World
        run: echo "Hello, World! This is a scheduled greeting from GitHub Actions. Triggered by: ${{ github.event_name }}"
      
      - name: Show system info
        run: |
          echo "Running on: $(uname -a)"
          echo "Current directory: $(pwd)"
          echo "Files in current directory:"
          ls -la
      
      - name: Display GitHub context
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Event name: ${{ github.event_name }}"
          echo "Actor: ${{ github.actor }}"
          echo "Workflow run ID: ${{ github.run_id }}"