name: Hello World Workflow

# This workflow runs when you push to the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual triggering of the workflow

# A workflow can have multiple jobs
jobs:
  hello-job:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks
    steps:
    # This action checks out your repository code
    - name: Checkout code
      uses: actions/checkout@v4
    
    # This step runs a simple command
    - name: Say hello
      run: echo "Hello, GitHub Actions! Triggered by:${{ github.event_name }}"
    
    # This step shows some system information
    - name: Show system info
      run: |
        echo "Running on: $(uname -a)"
        echo "Current directory: $(pwd)"
        echo "Files in current directory:"
        ls -la
    
    - name: Display GitHub context
      run: |
        echo "Repository: ${{ github.repository }}"
        echo "Event name: ${{ github.event_name }}"
        echo "Actor: ${{ github.actor }}"
        echo "Workflow run ID: ${{ github.run_id }}"